version: '3.5'

services:

  todo-app:
    container_name: todo-app
    image: webdevops/php-apache:7.4
    volumes:
      - .:/var/www/html
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html
    ports:
      - 80:80